<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_btn btn--full</name>
   <tag></tag>
   <elementGuidId>1b7f7614-c051-4181-bc1a-bb1f4e8189f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecoverPasswordForm > div.form-vertical > form > p > input.btn.btn--full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Gửi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Gửi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9054721c-ea3d-4e36-ad84-a7cdbe01da0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>44a621ff-b190-4a33-9665-20eafa45ff6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--full</value>
      <webElementGuid>bf0894ca-6a8b-4c82-9f6d-72851cf2a1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Gửi</value>
      <webElementGuid>6235eb00-9765-43fb-8e86-3ea32bdc28c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecoverPasswordForm&quot;)/div[@class=&quot;form-vertical&quot;]/form[1]/p[1]/input[@class=&quot;btn btn--full&quot;]</value>
      <webElementGuid>2f34b076-c62b-490f-8d9a-9d41bfa61650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Gửi']</value>
      <webElementGuid>b1c939b0-49e3-40aa-9498-1c0134bed3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RecoverPasswordForm']/div/form/p/input</value>
      <webElementGuid>0a948769-3103-40f3-96e9-a3de90429c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/p/input</value>
      <webElementGuid>dbb7f4d9-85c0-44eb-851d-cc60c686f50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>26ef8232-3a69-422c-b8a4-3b2bbf5af184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
