<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ngn nm s Vit - Nh Hu L - L Trung H_1062826747</name>
   <tag></tag>
   <elementGuidId>d2126fca-8533-4caf-bca8-9e4e6747285f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='1062826747']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1062826747</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ngàn năm sử Việt - Nhà Tây Sơn - Lưỡi gươm nhân ái&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1b6963a-7386-424c-9d6c-141b393a777f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1062826747</value>
      <webElementGuid>7a5ca351-41e5-4949-a2ab-bcb0daa62320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyload</value>
      <webElementGuid>7438c3d0-42c2-47ea-a818-f6225e50a6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000343865/product/ngan-nam-su-viet_nha-tay-son_luoi-guom-nhan-ai_bd83a62772f74233903db1c848292357_large.jpg</value>
      <webElementGuid>90d9cca8-2ef6-4c67-b7f0-f41987bb0578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000343865/product/ngan-nam-su-viet_nha-tay-son_luoi-guom-nhan-ai_bd83a62772f74233903db1c848292357_large.jpg</value>
      <webElementGuid>b886361d-d71b-4297-8eba-6df7d145aee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ngàn năm sử Việt - Nhà Tây Sơn - Lưỡi gươm nhân ái</value>
      <webElementGuid>ef0a052e-a0ac-4a05-92c6-9273ba6e70ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1062826747&quot;)</value>
      <webElementGuid>92e26234-d0be-439a-a322-0efa223817d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='1062826747']</value>
      <webElementGuid>b43cbaa2-a335-4a22-ab35-4e09478d7d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='owl-home-pro-products-slider-2']/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>38130bb6-ab58-4ab7-b4b5-0bfafe3712b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ngàn năm sử Việt - Nhà Tây Sơn - Lưỡi gươm nhân ái']</value>
      <webElementGuid>5849ae94-0cad-4618-a559-4fba95eb8c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>56ea568c-6337-42b7-b0d5-a3f1efce9859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '1062826747' and @src = '//product.hstatic.net/200000343865/product/ngan-nam-su-viet_nha-tay-son_luoi-guom-nhan-ai_bd83a62772f74233903db1c848292357_large.jpg' and @alt = 'Ngàn năm sử Việt - Nhà Tây Sơn - Lưỡi gươm nhân ái']</value>
      <webElementGuid>8f3d93ba-abd4-4450-a2f5-3f4c072b971e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
