<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SCH MI_1062713366</name>
   <tag></tag>
   <elementGuidId>bc912136-ba83-47ac-9b3d-1de219df3ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='1062713366']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1062713366</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tất tần tật Tết ta&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>05b4595d-243f-4fd0-b862-e5e759835a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1062713366</value>
      <webElementGuid>8abbd408-1583-418c-8370-08141603a265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyload</value>
      <webElementGuid>4a6d0b6c-531c-46e7-88fa-9e85eb8094e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000343865/product/tat-tan-tat-tet-ta_bia_1aa0a46182f04d0596a4ca276772ccae_large.jpg</value>
      <webElementGuid>22737db9-e08d-47aa-af19-53ac158b9e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000343865/product/tat-tan-tat-tet-ta_bia_1aa0a46182f04d0596a4ca276772ccae_large.jpg</value>
      <webElementGuid>0707f6a4-922c-44a9-b004-82aaa17669c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tất tần tật Tết ta</value>
      <webElementGuid>7f0d5aa0-7350-4c54-8455-69173f240388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1062713366&quot;)</value>
      <webElementGuid>2605d80d-714c-4157-a544-88e7cc2d4146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='1062713366']</value>
      <webElementGuid>c31da36a-305d-42d9-8262-9e9e2e0defff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='owl-home-pro-products-slider-2']/div/div/div/div/div/div/a/img</value>
      <webElementGuid>0147b4f4-5a6c-4dc1-9459-33d192638402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Tất tần tật Tết ta'])[2]</value>
      <webElementGuid>b90ce8eb-0a12-4176-bba6-04cb847966f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/a/img</value>
      <webElementGuid>363378e6-6af1-4e58-b11f-79cd02735cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '1062713366' and @src = '//product.hstatic.net/200000343865/product/tat-tan-tat-tet-ta_bia_1aa0a46182f04d0596a4ca276772ccae_large.jpg' and @alt = 'Tất tần tật Tết ta']</value>
      <webElementGuid>afef1cf3-375d-4800-9bcc-0f6564f40f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
