// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DangNhap1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void dangNhap1() {
    driver.Navigate().GoToUrl("https://nxbkimdong.com.vn/");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 660);
    driver.FindElement(By.LinkText("Đăng nhập")).Click();
    driver.FindElement(By.Id("CustomerEmail")).SendKeys("anhle06042004@gmail.com");
    driver.FindElement(By.Id("CustomerPassword")).Click();
    driver.FindElement(By.Id("CustomerPassword")).SendKeys("Lethianh12345");
    driver.FindElement(By.CssSelector("p:nth-child(7) > .btn")).Click();
  }
}
