<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_t cu hi</name>
   <tag></tag>
   <elementGuidId>0f16bab9-69d4-41e0-8a76-e7dde5eea9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='startbap_product_reviews']/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.starbap-ask-question-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đặt câu hỏi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>209d7d7a-7ba0-464d-9b9a-9f2fb31b8ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0c060365-ff17-4728-a92a-a4bafcc9cb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>starbap-ask-question-btn</value>
      <webElementGuid>69c0af6c-a2f5-43fe-909e-731524189bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt câu hỏi</value>
      <webElementGuid>f2425d6b-cbd9-4e01-8c95-a7b96d96ee16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startbap_product_reviews&quot;)/div[@class=&quot;starbap-rev-widg__header&quot;]/a[@class=&quot;starbap-ask-question-btn&quot;]</value>
      <webElementGuid>73b4ab16-5bf3-461b-85b9-8df1cb044e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='startbap_product_reviews']/div[2]/a</value>
      <webElementGuid>4f9edb52-8c11-4e7f-8a64-bbd049c2925e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đặt câu hỏi')]</value>
      <webElementGuid>38bb8ace-d71a-47af-bdb9-504f8652f556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dựa trên 0 đánh giá'])[1]/following::a[1]</value>
      <webElementGuid>ebf919e8-45cd-49a4-bbbc-18e048b11468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá sản phẩm'])[1]/following::a[6]</value>
      <webElementGuid>033f07a6-1000-4b57-8f98-f9f5e137a03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên'])[1]/preceding::a[2]</value>
      <webElementGuid>6b1384e0-4551-4a8b-92a3-e4ea66032722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::a[2]</value>
      <webElementGuid>6a06b8ca-9e26-4930-9944-9991804a66b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đặt câu hỏi']/parent::*</value>
      <webElementGuid>e1413492-0579-4f09-8db5-98aee8100c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>3f098878-ebea-4d14-8acc-26168be2f998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>636441c6-6959-48bc-a790-e4eb92372d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Đặt câu hỏi' or . = 'Đặt câu hỏi')]</value>
      <webElementGuid>f63e9013-be53-492b-b6b7-322fd1f5d269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
