<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tn_reviewer_name</name>
   <tag></tag>
   <elementGuidId>606a29a7-6799-4a87-98e7-06ca4918cea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='reviewer_name'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.starbap-question-form > div.starbap-form__name-fieldset > input[name=&quot;reviewer_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Nhập tên của bạn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcf93885-2e1c-42d1-82d4-7746eeef5d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reviewer_name</value>
      <webElementGuid>a6941de0-de3a-4b67-b25e-dcb05b7ff20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04061127-7b0c-4696-93b5-08fa7ffa4fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>492d4835-0efc-413e-978d-329d589087d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên của bạn</value>
      <webElementGuid>fecca6b8-f813-49b5-bbf7-3824816f9b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startbap_product_reviews&quot;)/div[@class=&quot;starbap-rev-widg__header&quot;]/div[@class=&quot;starbap-question-form-wrapper&quot;]/form[@class=&quot;starbap-question-form&quot;]/div[@class=&quot;starbap-form__name-fieldset&quot;]/input[1]</value>
      <webElementGuid>9269b87f-70fc-438f-aa79-87b5c45902a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='reviewer_name'])[2]</value>
      <webElementGuid>6df65ce9-b740-433d-9055-90ce9a821930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='startbap_product_reviews']/div[2]/div[4]/form/div/input</value>
      <webElementGuid>c4ca8419-4efd-4af2-a625-04b2bcb225ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/input</value>
      <webElementGuid>cb28f6ef-3fba-43c1-8fc8-e46c3d00645d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reviewer_name' and @type = 'text' and @placeholder = 'Nhập tên của bạn']</value>
      <webElementGuid>6ba701cb-4811-42f0-b80b-cc1032a0d7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
