<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi_reviewer_phone</name>
   <tag></tag>
   <elementGuidId>66da9dfa-0efc-4b7a-ba30-58807c836fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='reviewer_phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.starbap-question-form > div.starbap-form__phone-fieldset > input[name=&quot;reviewer_phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Nhập số điện thoại của bạn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c28d7439-5e19-4c77-ae04-4b0fa6b34fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reviewer_phone</value>
      <webElementGuid>1c1075a6-87d0-4d1b-8fda-8e50e50018eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>1d8915b9-6bd1-4b03-8fad-2c66ace65182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập số điện thoại của bạn</value>
      <webElementGuid>9cc77f81-88fe-4ea5-9a2b-ea108301b8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>274bdb2f-f537-49de-8fec-ee0f64385595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startbap_product_reviews&quot;)/div[@class=&quot;starbap-rev-widg__header&quot;]/div[@class=&quot;starbap-question-form-wrapper&quot;]/form[@class=&quot;starbap-question-form&quot;]/div[@class=&quot;starbap-form__phone-fieldset&quot;]/input[1]</value>
      <webElementGuid>ea13cd37-8ce8-467a-8bed-57b7552aa346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='reviewer_phone'])[2]</value>
      <webElementGuid>37e7ed5b-526b-4982-a8e1-d6242244ac38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='startbap_product_reviews']/div[2]/div[4]/form/div[3]/input</value>
      <webElementGuid>cab39497-3ab7-48ca-af94-f0af6aeb0b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div[3]/input</value>
      <webElementGuid>c75703bc-59c5-4222-a32e-409e69dd1256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reviewer_phone' and @type = 'phone' and @placeholder = 'Nhập số điện thoại của bạn']</value>
      <webElementGuid>aa7d662b-92c3-4d00-b3c7-43f7a7cf2231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
