<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_reviewer_email</name>
   <tag></tag>
   <elementGuidId>af45ddfe-cc62-4b26-9826-8064cfba7934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='reviewer_email'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.starbap-question-form > div.starbap-form__email-fieldset > input[name=&quot;reviewer_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;hi@example.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28b5718c-a5ea-44d8-b728-05905f9b2d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reviewer_email</value>
      <webElementGuid>0f90e97c-c2f6-4373-b85c-aa07c83b840d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9921589f-fbc4-4753-9e84-8d3c54741f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>hi@example.com</value>
      <webElementGuid>891f800f-b90a-4f27-a708-83755651209b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startbap_product_reviews&quot;)/div[@class=&quot;starbap-rev-widg__header&quot;]/div[@class=&quot;starbap-question-form-wrapper&quot;]/form[@class=&quot;starbap-question-form&quot;]/div[@class=&quot;starbap-form__email-fieldset&quot;]/input[1]</value>
      <webElementGuid>eb48a45e-31d2-41cb-bf56-3c9720547765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='reviewer_email'])[2]</value>
      <webElementGuid>c74e37b6-5114-4de9-8ff1-ae4cae119557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='startbap_product_reviews']/div[2]/div[4]/form/div[2]/input</value>
      <webElementGuid>8beeed11-cfca-4a12-b846-13f47aa3c6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div[2]/input</value>
      <webElementGuid>8edda1f7-1f9e-4e25-af94-6bf4fbc3e8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reviewer_email' and @type = 'email' and @placeholder = 'hi@example.com']</value>
      <webElementGuid>45761e71-e0df-49ff-b3ae-c666fd5ef8b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
