<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Ni dung_question_content</name>
   <tag></tag>
   <elementGuidId>b9290847-c679-4cbb-88a6-b2c9518de96d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='question_content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;question_content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Viết câu hỏi của bạn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fd80cbc3-7552-4ace-b1e0-44c39224902a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>821cc8bb-063e-4a7f-acf4-85d57aa0adf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question_content</value>
      <webElementGuid>c4bfe822-5003-4084-8fee-f69c27c22648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Viết câu hỏi của bạn</value>
      <webElementGuid>992a5996-e945-4f75-b7ca-a7d7a4db0f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8439cb55-7145-4e15-a828-f94c67b1c7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startbap_product_reviews&quot;)/div[@class=&quot;starbap-rev-widg__header&quot;]/div[@class=&quot;starbap-question-form-wrapper&quot;]/form[@class=&quot;starbap-question-form&quot;]/div[@class=&quot;starbap-form__question-fieldset&quot;]/textarea[1]</value>
      <webElementGuid>3ea7b4b1-c5d1-450f-980a-e1cb1762a243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='question_content']</value>
      <webElementGuid>d75ed9bd-f5a6-43db-bdea-4e46f14490d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='startbap_product_reviews']/div[2]/div[4]/form/div[4]/textarea</value>
      <webElementGuid>2ecf1168-7f11-492b-bdf7-6cb5217bd8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>b708fdbc-eecc-4d7a-9866-62062620a725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'question_content' and @placeholder = 'Viết câu hỏi của bạn']</value>
      <webElementGuid>18648ead-f5d7-4a3c-a292-9eda98a06bcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
